# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "marimo>=0.19.0",
#     "matplotlib==3.10.8",
#     "numpy==2.4.2",
# ]
# ///

import marimo

__generated_with = "0.20.4"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    import numpy as np
    import matplotlib.pyplot as plt

    return mo, np


@app.cell
def _(mo):
    mo.md(r"""
    # Homework 1
    Due Wednesday January 21, 2026

    Reading:
    * Required: Lecture Notes 2
    * Required: Lecture Slides 2
    * Optional: ITILA 26
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 1. (ECCMMA 16.4)
    Consider the functions

    $$
    f(x_1, x_2, \ldots, x_9) = f_1(x_1, x_3) f_2(x_1, x_4, x_5) f_3(x_1, x_6, x_7) f_4(x_4, x_8, x_9)
    $$

    and

    $$
    g_1(x_1) = \sum_{x_9 : x_2 \setminus x_1} f(x_1, x_2, \ldots, x_9).
    $$

    Assume that each $x_i$ comes from an alphabet $\mathcal{X}$ with $|\mathcal{X}| = q$.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(a)** Determine the number of computations required to compute $g_1(x_1)$ for all $x_1 \in \mathcal{X}$ if the factorization is not used.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(b)** Draw the factor graph associated with the given factorization of $f$.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(c)** What is the complexity of computing $g_1(x_1)$ for all $x_1 \in \mathcal{X}$ with message passing if only the relevant messages are computed? Determine the messages passed on each edge of the tree for this computation.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(d)** If only the relevant messages are computed, how many additional computations are required to compute

    $$
    g_7(x_7) = \sum_{x_9 : x_1 \setminus x_7} f(x_1, x_2, \ldots, x_9)?
    $$
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 2. (ECCMMA 16.7)
    Let $P_{X_1, X_2, X_3, X_4}(x_1, x_2, x_3, x_4)$ be a joint probability mass function for the random variables $X_1, X_2, X_3, X_4$.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(a)** Draw the (un)factor graph representing $P_{X_1, \ldots, X_4}(x_1, x_2, x_3, x_4)$.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(b)** Draw the factor graph representing the standard decomposition

    $$
    P_{X_1, \ldots, X_4}(x_1, x_2, x_3, x_4) = P_{X_1}(x_1) P_{X_2|X_1}(x_2|x_1) P_{X_3|X_1,X_2}(x_3|x_1, x_2) P_{X_4|X_1,X_2,X_3}(x_4|x_1, x_2, x_3).
    $$
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(c)** Assume $X_1 \to X_2 \to X_3 \to X_4$ form a Markov chain and draw the factor graph associated with the factorization

    $$
    P_{X_1, \ldots, X_4}(x_1, x_2, x_3, x_4) = P_{X_1}(x_1) P_{X_2|X_1}(x_2|x_1) P_{X_3|X_2}(x_3|x_2) P_{X_4|X_3}(x_4|x_3).
    $$
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(d)** Suppose that the $X_i$ are observed indirectly through $Y_i \sim P_{Y_i|X_i}(y|x) = p(y_i|x_i)$. Draw the factor graph for the hidden Markov model (HMM) implied by the factorization

    $$
    P_{X_1,\ldots,X_4,Y_1,\ldots,Y_4}(x_1, \ldots, x_4, y_1, \ldots, y_4) = \prod_{i=1}^4 P_{X_i|X_{i-1}}(x_i|x_{i-1}) p(y_i|x_i),
    $$

    where it is assumed that $P_{X_1|X_0}(x_1|x_0) = P_{X_1}(x_1)$ (e.g., $X_1$ is independent of $X_0$).
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 3. (FGML 1.3)
    Once upon a time, your friendly neighborhood TA was intent on world domination, but now she just wants to graduate. Her first step, obviously, was to build a graphical model, as shown below. The variables being: Graduate (G), which depends on papers (P) and proposal (R). As we know, papers and theorems (T) are both generated by drinking lots of coffee (C). And all grad students are dependent on free coffee provided by the university (U), which also depends on their favorite coffee shop being open (D). All the variables are binary valued {T, F}. The CPT parameters are:

    $$
    P(U = T) = 0.1
    $$

    $$
    P(D = T \mid U = T) = 0.6, \quad P(D = T \mid U = F) = 0.5
    $$

    $$
    P(C = T \mid U = T, D = T) = 0.7, \quad P(C = T \mid U = T, D = F) = 0.5
    $$

    $$
    P(C = T \mid U = F, D = T) = 0.6, \quad P(C = T \mid U = F, D = F) = 0.05
    $$

    $$
    P(P = T \mid C = T) = 0.8, \quad P(P = T \mid C = F) = 0.6
    $$

    $$
    P(T = T \mid C = T) = 0.7, \quad P(T = T \mid C = F) = 0.6
    $$

    $$
    P(R = T \mid P = T) = 0.7, \quad P(R = T \mid P = F) = 0.1
    $$

    $$
    P(G = T \mid P = T, R = T) = 0.9, \quad P(G = T \mid P = T, R = F) = 0.3
    $$

    $$
    P(G = T \mid P = F, R = T) = 0.5, \quad P(G = T \mid P = F, R = F) = 0.1
    $$

    Help your TA make some urgent inferences about her graduation plans.

    **(a)** How likely is the TA to graduate if her coffee supply runs out? $P(G = T \mid C = F) = ?$

    **(b)** How likely is the TA to graduate if Tazzo is open all the time? $P(G = T \mid D = T) = ?$

    **(c)** Should we even be worried about her coffee supply running out? $P(C = T) = ?$

    **(d)** If she is writing theorems, does this mean she will also publish? $P(P = T \mid T = T) = ?$

    Additionally, report the ordering used and the factors produced after eliminating each variable for the first query $[P(G = T \mid C = F)]$.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(np):
    # TODO: Implement variable elimination for the Bayesian network
    # Hint: define CPTs as numpy arrays and implement factor marginalization

    # CPTs
    P_U = np.array([0.9, 0.1])  # P(U=F), P(U=T)

    # P(D|U): shape [U, D]
    P_D_given_U = np.array([[0.5, 0.5],   # U=F: P(D=F), P(D=T)
                             [0.4, 0.6]])  # U=T: P(D=F), P(D=T)

    # TODO: define remaining CPTs and implement variable elimination
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 4. (MCT 2.4) (Hansel And Gretel Take A Field Trip In the Dark Forest)
    Hansel and Gretel, together with their classmates, take a field trip. The forest in which they are walking is so dark that each child can only see his/her immediate neighbors. Assume that communication is limited to these nearest neighbors as well and that the whole group of schoolchildren forms a tree (in the graph sense) with respect to this neighborhood structure.

    Construct a message-passing algorithm that allows the children to count all their classmates in a distributed fashion and determine if any children were eaten by the wolf. What is the initialization and what are the message-passing rules? Can you modify the algorithm to only count a prescribed subset, e.g., the set of girls?
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 5. (FGML 1.5)
    Consider an undirected graph $G = (V, E)$ with $V = \{1, \ldots, n\}$ and edges $E$. An independent set is a subset $S \subseteq V$ such that no edge has both endpoints in $S$. In this problem, you will model independent sets using a pairwise factor graph and use message passing ideas on a tree.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(a) Binary encoding.** Introduce binary variables $X_i \in \{0, 1\}$ for each $i \in V$ where $X_i = 1$ means "vertex $i$ is chosen." Write a pairwise factor-graph representation of the constraint "$X$ encodes an independent set" using only pairwise factors over edges.

    More concretely, define factors $\psi_{ij}(x_i, x_j)$ for each $(i, j) \in E$ so that

    $$
    f(x) = \prod_{(i,j) \in E} \psi_{ij}(x_i, x_j)
    $$

    is equal to 1 if $x = (x_1, \ldots, x_n)$ is an independent-set indicator and 0 otherwise. Give an explicit formula for $\psi_{ij}$.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(b) Counting independent sets as a partition function.** Using the factors from part (a), define a distribution

    $$
    p(x) = \frac{1}{Z} \prod_{(i,j) \in E} \psi_{ij}(x_i, x_j),
    $$

    and explain why the normalizing constant

    $$
    Z = \sum_{x \in \{0,1\}^n} \prod_{(i,j) \in E} \psi_{ij}(x_i, x_j)
    $$

    counts the number of independent sets of $G$.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(c) The weighted (hard-core) variant.** Fix a parameter $\lambda > 0$ and define unary factors

    $$
    \phi_i(x_i) = \lambda^{x_i} \quad (i \in V).
    $$

    Consider the weighted model

    $$
    p_\lambda(x) = \frac{1}{Z(\lambda)} \left[ \prod_{i \in V} \phi_i(x_i) \right] \left[ \prod_{(i,j) \in E} \psi_{ij}(x_i, x_j) \right].
    $$

    **i.** Interpret $Z(\lambda)$ as a generating function for independent sets by size.

    **ii.** Give an expression for $\mathbb{E}_{p_\lambda}\left[\sum_{i \in V} X_i\right]$ in terms of $Z(\lambda)$ and $\lambda$ (hint: differentiate $\log Z(\lambda)$).
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **(d) Exact computation on a small tree.** Consider a tree $T$ with vertex set $\{1, 2, 3, 4, 5\}$ where vertex 1 is connected to vertices 2 and 3, vertex 2 is connected to vertices 4 and 5 (in addition to 1). Use the pairwise-factor formulation from parts (a)–(c) with the weighted hard-core model parameter $\lambda > 0$.

    **(i) Set up sum-product messages.** Root the tree at vertex 1 and direct messages toward the root. For an edge $i$–$j$, define the message from $i$ to $j$ as

    $$
    m_{i \to j}(x_j) := \sum_{x_i \in \{0,1\}} \phi_i(x_i) \psi_{ij}(x_i, x_j) \prod_{k \in N(i) \setminus \{j\}} m_{k \to i}(x_i),
    $$

    where $N(i)$ are the neighbors of $i$ in $T$. Write out $m_{4 \to 2}$ and $m_{5 \to 2}$ explicitly (as two numbers each, one for $x_2 = 0$ and one for $x_2 = 1$).

    **(ii) Compute $Z(\lambda)$ exactly.** Compute all messages up to the root and then compute

    $$
    Z(\lambda) = \sum_{x_1 \in \{0,1\}} \phi_1(x_1) \prod_{k \in N(1)} m_{k \to 1}(x_1).
    $$

    Give your final answer as a polynomial in $\lambda$ (simplified).

    **(iii) Unweighted counting as a check.** Evaluate your expression at $\lambda = 1$ to obtain the number of independent sets of $T$.

    **(iv) A marginal probability.** Compute the marginal $p_\lambda(X_1 = 1)$. Your final answer should be a rational function in $\lambda$.

    **(v) Sampling.** Describe how this could be used to efficiently sample from the set of independent sets.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    **Solution:**
    """)
    return


@app.cell
def _():
    # TODO: Implement sum-product message passing on the tree for the hard-core model
    # Tree edges: (1,2), (1,3), (2,4), (2,5) — using 0-indexed: (0,1),(0,2),(1,3),(1,4)

    def psi(xi, xj):
        """Hard-core constraint: 1 if not both 1, else 0."""
        return 0 if (xi == 1 and xj == 1) else 1

    def phi(xi, lam):
        """Unary factor: lambda^xi."""
        return lam ** xi

    def compute_Z(lam):
        # TODO: implement sum-product and compute Z(lambda)
        pass

    # Test at lambda=1 to count independent sets
    print("Z(1) =", compute_Z(1.0))
    return


if __name__ == "__main__":
    app.run()
